services:
  frontend:
    image: thomasnabil1/e-commerce-frontend:latest
    ports:
      - "8080:80"


  backend:
    image: thomasnabil1/e-commerce-backend:latest
    ports:
      - "3000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/E-commerce
    depends_on:
      - mongo

  mongo:
    image:  mongo:6
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: 