apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://tomasnabil01_db_user:GMAIg69JLs0glfnj@cluster0.oun6kc2.mongodb.net/ecommerce?appName=Cluster0"
