---
- name: Create app directory
  file:
    path: /app
    state: directory

- name: Copy docker-compose file
  copy:
    src: docker-compose.yml
    dest: /app/docker-compose.yml

- name: Pull Backend Image
  docker_image:
    name: thomasnabil1/e-commerce-backend:latest
    source: pull
    force_source: yes

- name: Pull Frontend Image
  docker_image:
    name: thomasnabil1/e-commerce-frontend:latest
    source: pull
    force_source: yes

- name: Run Docker Compose
  command: docker-compose up -d
  args:
    chdir: /app