---
- name: Install Docker
  yum:
    name: docker
    state: present

- name: Install pip
  yum:
    name: python3-pip
    state: present

- name: Install Python Docker SDK
  pip:
    name:
      - "urllib3<2"
      - docker
      - requests
    executable: pip3

- name: Start & Enable Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64
    dest: /usr/bin/docker-compose
    mode: '0755'