name: CI/CD Pipeline

on: 
  push: 
     branches:
       - main

jobs: 
  build-and-push:
     runs-on: ubuntu-latest

     steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secret.DOCKER_USERNAME }}
          password: ${{ secret.DOCKER_PASSWORD }}

      - name: build & push backend
        uses: docker/build-push-actions@v5
        with:
          context: ./backend
          push: true
          tags: tomasnabil1/e-commerce-backend:latest

      - name: build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./pages
          push: true
          tags: tomasnabil1/e-commerce-frontend:latest